steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - kh2r_gen_seed
  - --runtime=python39
  - --trigger-http # Needed for first deploy
  - --timeout=3600
  # - --allow-unauthenticated # Will likely remove this after testing period
options:
  logging: CLOUD_LOGGING_ONLY